WITH R AS (
SELECT HISTORY_ID, CAR_TYPE, (DATEDIFF(END_DATE, START_DATE) + 1) * DAILY_FEE AS F,
(CASE 
	WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 
 	THEN "90일 이상"
	WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 
 	THEN "30일 이상"
	WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 
 	THEN "7일 이상"
 END
) AS D
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
)

SELECT HISTORY_ID, ROUND(F * (100-IFNULL(DISCOUNT_RATE, 0)) / 100) AS FEE
FROM R
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON R.D = P.DURATION_TYPE
WHERE R.CAR_TYPE = "트럭" AND R.CAR_TYPE = IFNULL(P.CAR_TYPE,"트럭")
ORDER BY 2 DESC, 1 DESC