WITH C AS 
(
    -- 대여 횟수가 5회 이상인 자동차들만 추출
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)

-- 월별 대여 횟수 구하기
SELECT 
    MONTH(START_DATE) AS MONTH, 
    H.CAR_ID, 
    COUNT(H.HISTORY_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN C ON H.CAR_ID = C.CAR_ID
WHERE DATE_FORMAT(START_DATE, '%Y-%m') BETWEEN '2022-08' AND '2022-10'
GROUP BY MONTH(START_DATE), H.CAR_ID
HAVING RECORDS > 0  -- 특정 월의 대여 횟수가 0인 경우 제외
ORDER BY MONTH(START_DATE), H.CAR_ID DESC;
