SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, 
M.S - SIZE_OF_COLONY AS YEAR_DEV, ID
FROM ECOLI_DATA E
LEFT JOIN 
(
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS S
    FROM ECOLI_DATA
    GROUP BY 1
) M 
ON YEAR(E.DIFFERENTIATION_DATE) = M.YEAR
ORDER BY 1, 2