SELECT 
(CASE
	WHEN SKILL_CODE &
 	(SELECT SUM(CODE)
	FROM SKILLCODES
	WHERE CATEGORY LIKE 'F%') > 0 AND SKILL_CODE & 
 	(SELECT CODE
    FROM SKILLCODES
    WHERE NAME = 'Python')
 	= 
 	(SELECT CODE
    FROM SKILLCODES
    WHERE NAME = 'Python')
	THEN 'A'
 	WHEN SKILL_CODE & 
 	(SELECT CODE
    FROM SKILLCODES
    WHERE NAME = 'C#')
 	=
 	(SELECT CODE
    FROM SKILLCODES
    WHERE NAME = 'C#')
 	THEN 'B'
 	WHEN SKILL_CODE &
 	(SELECT SUM(CODE)
	FROM SKILLCODES
	WHERE CATEGORY LIKE 'F%') > 0
 	THEN 'C'
 END) AS GRADE, ID, EMAIL
FROM DEVELOPERS D
JOIN SKILLCODES S ON D.SKILL_CODE & S.CODE
GROUP BY 1, 2, 3
HAVING GRADE IS NOT NULL
ORDER BY 1, 2